export {
  Dialog,
  DialogClose,
  type DialogCloseAsChildProps,
  type DialogCloseProps,
  DialogContent,
  type DialogContentAsChildProps,
  type DialogContentOwnProps,
  type DialogContentProps,
  DialogDescription,
  type DialogDescriptionAsChildProps,
  type DialogDescriptionProps,
  DialogOverlay,
  type DialogOverlayAsChildProps,
  type DialogOverlayOwnProps,
  type DialogOverlayProps,
  type DialogOwnProps,
  DialogPortal,
  type DialogPortalProps,
  type DialogProps,
  DialogTitle,
  type DialogTitleAsChildProps,
  type DialogTitleProps,
  DialogTrigger,
  type DialogTriggerAsChildProps,
  type DialogTriggerProps,
} from "@askrjs/ui/dialog";
