export {
  Slider,
  type SliderOrientation,
  type SliderOwnProps,
  type SliderProps,
  SliderRange,
  type SliderRangeAsChildProps,
  type SliderRangeProps,
  SliderThumb,
  type SliderThumbAsChildProps,
  type SliderThumbProps,
  SliderTrack,
  type SliderTrackAsChildProps,
  type SliderTrackProps,
} from "@askrjs/ui/slider";
