export {
  Table,
  type TableAsChildProps,
  TableBody,
  type TableBodyAsChildProps,
  type TableBodyProps,
  TableCaption,
  type TableCaptionAsChildProps,
  type TableCaptionProps,
  TableCell,
  type TableCellAsChildProps,
  type TableCellProps,
  TableFoot,
  type TableFootAsChildProps,
  type TableFootProps,
  TableHead,
  type TableHeadAsChildProps,
  TableHeaderCell,
  type TableHeaderCellAsChildProps,
  type TableHeaderCellProps,
  type TableHeadProps,
  type TableProps,
  TableRow,
  type TableRowAsChildProps,
  type TableRowProps,
} from "@askrjs/ui/table";
