import { describe, expect, it } from "vite-plus/test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { DOCS_DIR, PACKAGE_JSON } from "./test-paths";

const THEMES_DOC = join(DOCS_DIR, "askr-themes.md");
const THEMING_DOC = join(DOCS_DIR, "theming.md");
const README_DOC = join(DOCS_DIR, "README.md");
const TOKENS_DOC = join(DOCS_DIR, "tokens.md");

describe("docs surface", () => {
  it("should documents curated entrypoints instead of a components catch-all", () => {
    const pkg = JSON.parse(readFileSync(PACKAGE_JSON, "utf-8")) as {
      exports?: Record<string, unknown>;
    };

    expect(pkg.exports?.["./theme"]).toBeTruthy();
    expect(pkg.exports?.["./core"]).toBeTruthy();
    expect(pkg.exports?.["./controls"]).toBeTruthy();
    expect(pkg.exports?.["./surfaces"]).toBeTruthy();
    expect(pkg.exports?.["./feedback"]).toBeUndefined();
    expect(pkg.exports?.["./navs"]).toBeTruthy();
    expect(pkg.exports?.["./overlays"]).toBeTruthy();
    expect(pkg.exports?.["./layouts"]).toBeUndefined();
    expect(pkg.exports?.["./shells"]).toBeUndefined();
    expect(pkg.exports?.["./logos"]).toBeUndefined();
    expect(pkg.exports?.["./components"]).toBeUndefined();
  });

  it("should documents the same curated families and canonical names", () => {
    const themesDoc = readFileSync(THEMES_DOC, "utf-8");
    const themingDoc = readFileSync(THEMING_DOC, "utf-8");
    const readmeDoc = readFileSync(README_DOC, "utf-8");
    const tokensDoc = readFileSync(TOKENS_DOC, "utf-8");

    expect(themesDoc).toContain("## Design Model");
    expect(themesDoc).toContain("## Public API");
    expect(themesDoc).toContain("## Block");
    expect(themesDoc).toContain("## Semantic Wrappers");
    expect(themesDoc).toContain("## Common Composition");
    expect(themesDoc).toContain("## Status And Overlays");
    expect(themesDoc).toContain("`Block` is the only layout engine.");
    expect(themesDoc).toContain("@askrjs/themes/core");
    expect(themesDoc).toContain("@askrjs/themes/controls");
    expect(themesDoc).toContain("@askrjs/themes/surfaces");
    expect(themesDoc).not.toContain("@askrjs/themes/feedback");
    expect(themesDoc).toContain("@askrjs/themes/navs");
    expect(themesDoc).toContain("@askrjs/themes/overlays");
    expect(themesDoc).not.toContain("@askrjs/themes/layouts");
    expect(themesDoc).not.toContain("@askrjs/themes/shells");
    expect(themesDoc).not.toContain("@askrjs/themes/logos");
    expect(themesDoc).toContain("Block,");
    expect(themesDoc).toContain("Container,");
    expect(themesDoc).toContain("Header,");
    expect(themesDoc).toContain("Main,");
    expect(themesDoc).toContain("Section,");
    expect(themesDoc).toContain("Aside,");
    expect(themesDoc).toContain("Sidebar,");
    expect(themesDoc).toContain("Navbar,");
    expect(themesDoc).toContain("NavBrand,");
    expect(themesDoc).toContain("NavDropdown,");
    expect(themesDoc).toContain("NavGroup,");
    expect(themesDoc).toContain("NavItem,");
    expect(themesDoc).toContain("Page,");
    expect(themesDoc).toContain("PageHeader,");
    expect(themesDoc).toContain("Toolbar,");
    expect(themesDoc).toContain("EmptyState,");
    expect(themesDoc).toContain("Use explicit prop names.");
    expect(themesDoc).toContain("Application-specific layouts stay as recipes");
    expect(themesDoc).toContain("NavLink");
    expect(themesDoc).toContain("InputGroup");
    expect(themesDoc).toContain("Field");
    expect(themesDoc).toContain("ListGroup");
    expect(themesDoc).toContain("Pagination");
    expect(themesDoc).toContain("Breadcrumb");
    expect(themesDoc).toContain("Spinner");
    expect(themesDoc).toContain("If the default theme styles a `@askrjs/ui` primitive");
    expect(themesDoc).toContain("app-facing import path for styled components");
    expect(themesDoc).toContain("Do not create a second `Modal` abstraction.");
    expect(themesDoc).toContain("Chips and tags stay as recipes for now.");

    expect(themingDoc).toContain("## Selector Contract");
    expect(themingDoc).toContain("## Cat Presets");
    expect(themingDoc).toContain("@askrjs/themes/presets");
    expect(themingDoc).toContain("`tabby`");
    expect(themingDoc).toContain("`ginger`");
    expect(themingDoc).toContain("`tuxedo`");
    expect(themingDoc).toContain("`calico`");
    expect(themingDoc).toContain("`torty`");
    expect(themingDoc).toContain("use `core` for structure");
    expect(themingDoc).toContain("Block");
    expect(themingDoc).toContain("Alert");
    expect(themingDoc).toContain("ButtonGroup");
    expect(themingDoc).toContain("InputGroup");
    expect(themingDoc).toContain("Field");
    expect(themingDoc).toContain("ListGroup");
    expect(themingDoc).toContain("Pagination");
    expect(themingDoc).toContain("CardActions");
    expect(themingDoc).toContain("Header");
    expect(themingDoc).toContain("Breadcrumb");
    expect(themingDoc).toContain("Spinner");
    expect(themingDoc).toContain("If the default theme styles a `@askrjs/ui` primitive");
    expect(themingDoc).toContain("Use `controls` for styled components such as Button, Input, Select");
    expect(themingDoc).toContain("as Alert, Badge, Card, CardActions");
    expect(themingDoc).toContain("`EmptyState` belongs to `core`");
    expect(themingDoc).toContain("`Dialog` is the canonical modal surface name");
    expect(themingDoc).toContain("Chips and tags should stay local recipes");

    expect(readmeDoc).toContain("@askrjs/themes/core");
    expect(readmeDoc).toContain("@askrjs/themes/navs");
    expect(readmeDoc).toContain("@askrjs/themes/surfaces");
    expect(readmeDoc).not.toContain("@askrjs/themes/feedback");
    expect(readmeDoc).toContain("@askrjs/themes/theme");
    expect(readmeDoc).toContain("@askrjs/themes/overlays");
    expect(readmeDoc).not.toContain("@askrjs/themes/layouts");
    expect(readmeDoc).not.toContain("@askrjs/themes/shells");
    expect(readmeDoc).not.toContain("@askrjs/themes/logos");
    expect(readmeDoc).toContain("ButtonGroup");
    expect(readmeDoc).toContain("InputGroup");
    expect(readmeDoc).toContain("Field");
    expect(readmeDoc).toContain("Pagination");
    expect(readmeDoc).toContain("Card");
    expect(readmeDoc).toContain("DropdownContent");
    expect(readmeDoc).toContain("KISS import path for styled app components");
    expect(readmeDoc).toContain("Keep chips/tags as recipes");
    expect(themingDoc).not.toContain("@askrjs/themes/feedback");

    expect(tokensDoc).toContain("## Semantic Registry");
    expect(tokensDoc).toContain("tabby");
    expect(tokensDoc).toContain("ginger");
    expect(tokensDoc).toContain("tuxedo");
    expect(tokensDoc).toContain("calico");
    expect(tokensDoc).toContain("torty");
    expect(tokensDoc).toContain("component-specific token");
    expect(tokensDoc).toContain("Color");
    expect(tokensDoc).toContain("Typography");
    expect(tokensDoc).toContain("Spacing");
    expect(tokensDoc).toContain("Density");
    expect(tokensDoc).toContain("Layout");
    expect(tokensDoc).toContain("Elevation");
    expect(tokensDoc).toContain("Focus");
    expect(tokensDoc).toContain("Motion");
    expect(tokensDoc).toContain("Z-index");
    expect(tokensDoc).toContain("State");
  });
});
